
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: taskly-with-js_development

test:
  <<: *default
  database: taskly-with-js_test

production:
  <<: *default
  database: taskly-with-js_production
  username: taskly-with-js
  password: <%= ENV['TASKLY-WITH-JS_DATABASE_PASSWORD'] %>
