# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bc885ef95b5c0b42f8033d03cc1e664281400aed06a98a976c345a8f96bdff6a16a3b14fd9a2bb071f2e0eefc1165c8b07e2ef5538e89c64d7c86d8ea451da6

test:
  secret_key_base: 5f1270c01faecbd2d4c11cdd76cf5fa4afd3860db8a87cc842ec337cfb0d0ce8cbd6151c133509976155ce91d1da8798691363c08f2458b48b6fcbdb2eeee873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
